import { ISettings } from '../../api/settings.ts';
import { IParentHeight } from '../layout/ParentHeight.ts';
import { ILiveWebSocket } from '../../live/ILiveWebSocket.ts';
import { IAccountApi } from '../../interfaces/apis/IAccountApi.ts';
import { IErrorApi } from '../../interfaces/apis/IErrorApi.ts';
import { IReportApi } from '../../interfaces/apis/IReportApi.ts';
import { ISaygApi } from '../../interfaces/apis/ISaygApi.ts';
import { ISeasonTemplateApi } from '../../interfaces/apis/ISeasonTemplateApi.ts';
import { IDivisionApi } from '../../interfaces/apis/IDivisionApi.ts';
import { IGameApi } from '../../interfaces/apis/IGameApi.ts';
import { ILiveApi } from '../../interfaces/apis/ILiveApi.ts';
import { INoteApi } from '../../interfaces/apis/INoteApi.ts';
import { ISeasonApi } from '../../interfaces/apis/ISeasonApi.ts';
import { IPlayerApi } from '../../interfaces/apis/IPlayerApi.ts';
import { ITeamApi } from '../../interfaces/apis/ITeamApi.ts';
import { ITournamentGameApi } from '../../interfaces/apis/ITournamentGameApi.ts';
import { IDataApi } from '../../interfaces/apis/IDataApi.ts';
import { IFeatureApi } from '../../interfaces/apis/IFeatureApi.ts';
import { IQueryApi } from '../../interfaces/apis/IQueryApi.ts';

export interface IDependencies {
    divisionApi: IDivisionApi;
    accountApi: IAccountApi;
    seasonApi: ISeasonApi;
    teamApi: ITeamApi;
    errorApi: IErrorApi;
    settings: ISettings;
    parentHeight: IParentHeight;
    tournamentApi: ITournamentGameApi;
    dataApi: IDataApi;
    gameApi: IGameApi;
    noteApi: INoteApi;
    playerApi: IPlayerApi;
    reportApi: IReportApi;
    saygApi: ISaygApi;
    templateApi: ISeasonTemplateApi;
    liveApi: ILiveApi;
    webSocket: ILiveWebSocket;
    featureApi: IFeatureApi;
    queryApi: IQueryApi;
}
