namespace CourageScores.Models.Dtos.Identity;

public enum AccessOption
{
    ManageAccess,
    ManageDivisions,
    ManageGames,
    ManageNotes,
    ManagePlayers,
    ManageScores,
    ManageSeasons,
    ManageTeams,
    RunReports,
    ExportData,
    ImportData,
    InputResults,
    ViewExceptions,
    RecordScoresAsYouGo,
    ManageTournaments,
    RunHealthChecks,
    ManageSeasonTemplates,
    ShowDebugOptions,
    ManageSockets,
    UseWebSockets,
    EnterTournamentResults,
    UploadPhotos,
    ViewAnyPhoto,
    DeleteAnyPhoto,
    BulkDeleteLeagueFixtures,
    ManageFeatures,
    KioskMode,
    AnalyseMatches,
    RunDataQueries,
    LoginServiceAccounts,
}
