name: Run audit tasks
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      branch-name:
        required : true
        type: string
      commit-sha:
        required: true
        type: string
jobs:
  solution:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Check file .cs sizes
        if: ${{ github.event.inputs.ignore_sizes != 'true' }}
        shell: pwsh
        run: ./Scripts/BuildChecks.ps1 -ErrorThreshold 500 -WarningThreshold 450 -Extension '.cs'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_SHA: "${{ inputs.commit-sha }}"

      - name: npm install
        shell: pwsh
        working-directory: ./CourageScores/ClientApp
        run: npm ci

      - name: Run npm prettier
        shell: pwsh
        run: ../../Scripts/NpmPrettier.ps1
        working-directory: ./CourageScores/ClientApp
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check .tsx file sizes
        if: ${{ github.event.inputs.ignore_sizes != 'true' }}
        shell: pwsh
        run: ./Scripts/BuildChecks.ps1 -ErrorThreshold 1000 -WarningThreshold 900 -Extension '.tsx'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_SHA: "${{ inputs.commit-sha }}"

      - name: Check .ts file sizes
        if: ${{ github.event.inputs.ignore_sizes != 'true' }}
        shell: pwsh
        run: ./Scripts/BuildChecks.ps1 -ErrorThreshold 500 -WarningThreshold 450 -Extension '.ts'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_SHA: "${{ inputs.commit-sha }}"

      - name: Run npm audit (app)
        shell: pwsh
        run: ../../Scripts/NpmAudit.ps1 -Project ClientApp
        working-directory: ./CourageScores/ClientApp
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run npm audit (behavioural tests)
        shell: pwsh
        run: ../Scripts/NpmAudit.ps1 -Project BehaviouralTests -Install
        working-directory: ./CourageScores.BehaviouralTests
        env:
          GITHUB_TOKEN: ${{ github.token }}
