name: Build

on:
  workflow_call:
    inputs:
      dotnet-root:
        required: true
        type: string

jobs:
  with-dotnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with dotnet
        run: dotnet build --configuration Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_NOLOGO: true

      - name: Test with dotnet
        run: dotnet test --configuration Release --logger:nunit --logger "trx;LogFileName=TestResults.trx" /p:CollectCoverage=true /p:CoverletOutput=Coverage/ /p:CoverletOutputFormat=lcov
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_NOLOGO: true

      - name: Publish dotnet coverage
        uses: coverallsapp/github-action@v2.3.0
        with:
            file: ./CourageScores.Tests/Coverage/coverage.info
            flag-name: dotnet
            parallel: true
            format: lcov

      - name: Publish nunit test results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: NUnitTestResults
          path: CourageScores.Tests/TestResults/TestResults.trx
