name: Build

on:
  workflow_call:
    inputs:
      dotnet-root:
        required: true
        type: string

jobs:
  with-dotnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build with dotnet
        run: dotnet build --configuration Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_NOLOGO: true

      - name: Test with dotnet
        run: dotnet test --configuration Release --logger:nunit /p:CollectCoverage=true /p:CoverletOutput=Coverage/ /p:CoverletOutputFormat=lcov
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_NOLOGO: true

      - name: Publish dotnet coverage
        uses: coverallsapp/github-action@v1
        with:
            path-to-lcov: ./CourageScores.Tests/Coverage/coverage.info
            flag-name: dotnet
            parallel: true
