name: Auto-create release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout all branches
        run: git fetch --depth=1

      - name: Create release if none exists
        shell: pwsh
        run: ./Scripts/CreateRelease.ps1
        env:
          GITHUB_TOKEN: ${{ github.token }}
