name: DEV

on:
  workflow_dispatch:
    inputs:
      deploy_dev:
        description: 'Deploy to dev?'
        required: false
        type: boolean
        default: true
      ignore_sizes:
        description: 'Ignore file sizes?'
        required: false
        type: boolean
        default: false
  pull_request:
    types: [opened,reopened,synchronize]
    branches:
      - 'main'

jobs:
  branch-name:
    uses: ./.github/workflows/get-branch-name.yml

  setup:
    needs: 
     - branch-name
    uses: ./.github/workflows/setup-workflow.yml
    with:
      branch-name: ${{ needs.branch-name.outputs.branch-name }}
      deploy-requested: ${{ github.event.inputs.deploy_dev }}

  build:
    needs: 
     - setup
     - branch-name
    uses: ./.github/workflows/build.yml
    with: 
      ignore_sizes: ${{ github.event.inputs.ignore_sizes }}

  publish:
    needs: 
     - branch-name
     - setup
    uses: ./.github/workflows/publish.yml
    with: 
      upload: ${{ needs.setup.outputs.deploy == 'true' }}
      branch-name: ${{ needs.branch-name.outputs.branch-name }}
      commit-sha: ${{ github.sha }}
      commit-date: ${{ needs.setup.outputs.commit-date }}

  report_tests:
    runs-on: ubuntu-latest
    name: report / test results
    if: always()

    needs:
     - publish
     - build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger test analysis
        shell: pwsh
        run: ./Scripts/TriggerTestFailureAnalysis.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_COMMENT_TOKEN: ${{ secrets.REPORT_FAILURES_PAT }}

  deploy:
    if: ${{ needs.setup.outputs.deploy == 'true' }}
    needs: 
      - branch-name
      - build
      - publish
    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: 'DEV'
      app-name: 'couragescoresdev'
    secrets:
      publish-profile: ${{ secrets.PUBLISHPROFILE_DEV }}

  report:
    needs: 
      - build
      - publish
    uses: ./.github/workflows/publish_coverage.yml
