name: DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_dev:
        description: 'Deploy to dev?'
        require: false
        type: boolean
        default: false
  pull_request:
    types: [opened,reopened,synchronize]

jobs:
  setup:
    needs: 
     - branch-name
    uses: ./.github/workflows/setup-workflow.yml
    with:
      branch-name: ${{ needs.branch-name.outputs.branch-name }}
      deploy-requested: ${{ github.event.inputs.deploy_dev }}

  build-and-upload:
    needs: 
     - setup
     - branch-name
    uses: ./.github/workflows/build.yml
    with: 
      dotnet-root: ${{ needs.setup.outputs.dotnet-root }}
      upload: ${{ needs.setup.outputs.deploy == 'true' }}
    secrets:
      google-oauth-id: ${{ secrets.GOOGLEOAUTHID }}
      google-oauth-secret: ${{ secrets.GOOGLEOAUTHSECRET }}
      debug-token: ${{ secrets.DEBUGTOKEN }}
      cosmos-databasename: ${{ secrets.COSMOSDB_DATABASENAME_DEV }}
      cosmos-key: ${{ secrets.COSMOSDB_KEY_DEV }}
      cosmos-url: ${{ secrets.COSMOSDB_URL_DEV }}

  branch-name:
    uses: ./.github/workflows/get-branch-name.yml

  deploy:
    if: ${{ needs.setup.outputs.deploy == 'true' }}
    needs: 
      - build-and-upload
      - branch-name
    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: 'DEV'
      app-name: 'couragescoresdev'
    secrets:
      publish-profile: ${{ secrets.PUBLISHPROFILE_DEV }}
