name: DEV

on:
  workflow_dispatch:
    inputs:
      deploy_dev:
        description: 'Deploy to dev?'
        required: false
        type: boolean
        default: true
  pull_request:
    types: [opened,reopened,synchronize]
    branches:
      - 'main'

jobs:
  branch-name:
    uses: ./.github/workflows/get-branch-name.yml

  setup:
    needs: 
     - branch-name
    uses: ./.github/workflows/setup-workflow.yml
    with:
      branch-name: ${{ needs.branch-name.outputs.branch-name }}
      deploy-requested: ${{ github.event.inputs.deploy_dev }}

  build:
    needs: 
     - setup
     - branch-name
    uses: ./.github/workflows/build.yml
    with: 
      dotnet-root: ${{ needs.setup.outputs.dotnet-root }}

  publish-coverage:
    needs:
      - publish
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Complete coverage collection
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true

  publish:
    needs: 
     - branch-name
     - setup
    uses: ./.github/workflows/publish.yml
    with: 
      upload: ${{ needs.setup.outputs.deploy == 'true' }}
      branch-name: ${{ needs.branch-name.outputs.branch-name }}
      commit-sha: ${{ github.sha }}
      commit-date: ${{ needs.setup.outputs.commit-date }}

  deploy:
    if: ${{ needs.setup.outputs.deploy == 'true' }}
    needs: 
      - branch-name
      - build
      - publish
    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: 'DEV'
      app-name: 'couragescoresdev'
    secrets:
      publish-profile: ${{ secrets.PUBLISHPROFILE_DEV }}
