name: Get branch name

on:
  workflow_call:
    outputs:
      branch-name: 
        value: ${{ jobs.get.outputs.branch-name }}

jobs:
  get:
    runs-on: windows-latest

    outputs:
      branch-name: ${{ steps.export-branch-name.outputs.branch-name }}

    steps:
      - name: Export branch name
        id: export-branch-name
        shell: bash
        run: |
          echo "branch_name=$(echo "$GITHUB_REF_NAME" | sed -r 's/\//_/g')" >> $GITHUB_OUTPUT