name: PROD

on:
  push:
    branches:
      - release

jobs:
  setup:
    uses: ./.github/workflows/setup-workflow.yml
    with:
      branch-name: 'release'
      deploy-requested: true

  build:
    needs: 
     - setup
    uses: ./.github/workflows/build.yml
    with: 
      dotnet-root: ${{ needs.setup.outputs.dotnet-root }}

  publish:
    uses: ./.github/workflows/publish.yml
    with: 
      upload: true

  deploy:
    needs: 
      - build
      - publish
    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: 'PROD'
      app-name: 'CourageScores'
    secrets:
      publish-profile: ${{ secrets.PUBLISHPROFILE_RELEASE }}
