name: PROD
permissions:
  contents: read
  pull-requests: write
  deployments: write

on:
  push:
    branches:
      - release

jobs:
  setup:
    uses: ./.github/workflows/setup-workflow.yml
    with:
      branch-name: 'release'
      deploy-requested: true

  build:
    needs: 
     - setup
    uses: ./.github/workflows/build.yml
    with: 
      ignore_sizes: true # ignoring sizes on a PROD build; they should have been picked up in UAT - also to reduce friction for any hotfixes

  publish:
    needs:
     - setup
    uses: ./.github/workflows/publish.yml
    with: 
      upload: true
      branch-name: 'release'
      commit-sha: ${{ github.sha }}
      commit-date: ${{ needs.setup.outputs.commit-date }}
      robots-tag-header: all
      frame-host-url: "http://thecourageleague.co.uk"

  report_tests:
    runs-on: ubuntu-latest
    name: report / test results

    needs:
     - publish
     - build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger test analysis
        if: success() || failure()
        shell: pwsh
        run: ./Scripts/TriggerTestFailureAnalysis.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_COMMENT_TOKEN: ${{ secrets.REPORT_FAILURES_PAT }}

  deploy:
    needs: 
      - build
      - publish
    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: 'PROD'
      app-name: 'CourageLeague'
    secrets:
      publish-profile: ${{ secrets.PUBLISHPROFILE_PROD }}

  report:
    needs: 
      - build
      - publish
    uses: ./.github/workflows/publish_coverage.yml
