name: PROD

on:
  push:
    branches:
      - release

jobs:
  setup:
    uses: ./.github/workflows/setup-workflow.yml
    with:
      branch-name: 'release'
      deploy-requested: true

  build:
    needs: 
     - setup
    uses: ./.github/workflows/build.yml
    with: 
      dotnet-root: ${{ needs.setup.outputs.dotnet-root }}

  publish:
    needs:
     - setup
    uses: ./.github/workflows/publish.yml
    with: 
      upload: true
      branch-name: 'release'
      commit-sha: ${{ github.sha }}
      commit-date: ${{ needs.setup.outputs.commit-date }}

  publish-coverage:
    needs:
      - publish
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Complete coverage report
        uses: coverallsapp/github-action@v1
        with:
          parallel-finished: true

  deploy:
    needs: 
      - build
      - publish
    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: 'PROD'
      app-name: 'CourageLeague'
    secrets:
      publish-profile: ${{ secrets.PUBLISHPROFILE_PROD }}
