name: Publish test results

on:
  workflow_run:
    workflows: ['DEV', 'UAT', 'PROD']
    types:
      - completed

jobs:
  report:
    name: 'Test Results (1.9.1)'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: dorny/test-reporter@v1.9.1
        with:
          artifact: NUnitTestResults
          name: NUnit Tests
          path: 'TestResults.trx'
          reporter: dotnet-trx
          fail-on-error: false

      - uses: dorny/test-reporter@v1.9.1
        with:
           artifact: JestTestResults
           name: Jest Tests
           path: '*.xml'
           reporter: jest-junit
           fail-on-error: false
