name: Publish and upload

on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean
      branch-name:
        required : true
        type: string
      commit-sha:
        required: true
        type: string
      commit-date:
        required: true
        type: string
  
jobs:
  with-dotnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dotnet publish
        run: dotnet publish --configuration Release --property PublishDir=myapp
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_NOLOGO: true
          REACT_APP_BRANCH: "${{ inputs.branch-name }}"
          REACT_APP_SHA: "${{ inputs.commit-sha }}"
          REACT_APP_DATE: "${{ inputs.commit-date }}"

      - name: Add coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./CourageScores/ClientApp/coverage/coverage-summary.json

      - name: Publish react coverage
        uses: coverallsapp/github-action@v1
        with:
           path-to-lcov: ./CourageScores/ClientApp/coverage/lcov.info
           debug: true
           base-path: ./CourageScores/ClientApp

      - name: Upload artifact for deployment job
        if: ${{ inputs.upload == true }}
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./CourageScores/myapp
          if-no-files-found: error
