name: Publish and upload

on:
  workflow_call:
    inputs:
      upload:
        required: true
        type: boolean
      branch-name:
        required : true
        type: string
      commit-sha:
        required: true
        type: string
  
jobs:
  with-dotnet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dotnet publish
        run: dotnet publish --configuration Release --property PublishDir=/myapp
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_NOLOGO: true
          REACT_APP_BRANCH: "${{ inputs.branch-name }}"
          REACT_APP_SHA: "${{ inputs.commit-sha }}"

#      - name: Report code coverage
#        uses: romeovs/lcov-reporter-action@v0.2.11
#        with:
#          lcov-file: ./CourageScores/ClientApp/coverage/lcov.info
#          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact for deployment job
        if: ${{ inputs.upload == true }}
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: /myapp
