name: Publish test coverage

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Complete coverage collection
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
