name: Post-release steps

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'release'
jobs:
  tag_merge_commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'release'

      - name: add tag and push
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
              git tag "$PR_TITLE"
              git push --tags

  close_milestone:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Close milestone for this release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: ./Scripts/CloseMilestone.ps1
      - name: Ensure at least 2 open milestones
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./Scripts/EnsureOpenMilestones.ps1 -MinOpen 2