name: Post-release steps

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'release'
jobs:
  tag_merge_commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'release'

      - name: add tag and push
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
              git tag "$PR_TITLE"
              git push --tags

  close_milestone:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: Akkjon/close-milestone@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          milestone_name: ${{ github.event.pull_request.title }}
          crash_on_missing: true