name: Setup workflow

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
      deploy-requested:
        required: false
        type: string
        default: 'true'
    outputs:
      dotnet-root: 
        value: ${{ jobs.dotnet.outputs.dotnet-root }}
      deploy:
        value: ${{ jobs.branch.outputs.deploy }}
      commit-date:
        value: ${{ jobs.branch.outputs.commit-date }}

jobs:
  dotnet:
    runs-on: ubuntu-latest

    outputs:
      dotnet-root: ${{ steps.export-dotnet-root.outputs.dotnet-root }}

    steps:
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Export dotnet-root
        id: export-dotnet-root
        run: echo "dotnet-root=${{ env.DOTNET_ROOT }}" >> $GITHUB_OUTPUT

  branch:
    runs-on: windows-latest

    outputs:
      deploy: ${{ steps.should-deploy.outputs.deploy }}
      commit-date: ${{ steps.export-commit-date.outputs.commit-date }}

    steps:
      - name: Print branch
        shell: bash
        run: |
          echo "branch-name=${{ inputs.branch-name }}"

      - name: Should deploy (branch name)
        if: ${{ inputs.branch-name == 'release' || inputs.branch-name == 'main' || inputs.deploy-requested == 'true' || inputs.deploy-requested == '' }}
        id: should-deploy
        shell: bash
        run: |
          echo "deploy=true" >> $GITHUB_OUTPUT

      - name: Export commit date
        id: export-commit-date
        shell: bash
        run: |
          echo "commit-date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT