name: Setup workflow
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
      deploy-requested:
        required: false
        type: string
        default: 'true'
    outputs:
      deploy:
        value: ${{ jobs.branch.outputs.deploy }}
      commit-date:
        value: ${{ jobs.branch.outputs.commit-date }}

jobs:
  branch:
    runs-on: ubuntu-latest

    outputs:
      deploy: ${{ steps.should-deploy.outputs.deploy }}
      commit-date: ${{ steps.export-commit-date.outputs.commit-date }}

    steps:
      - name: Print branch
        shell: bash
        run: |
          echo "branch-name=${{ inputs.branch-name }}"

      - name: Should deploy (branch name)
        if: ${{ inputs.branch-name == 'release' || inputs.branch-name == 'main' || inputs.deploy-requested == 'true' || inputs.deploy-requested == '' }}
        id: should-deploy
        shell: bash
        run: |
          echo "deploy=true" >> $GITHUB_OUTPUT

      - name: Export commit date
        id: export-commit-date
        shell: bash
        run: |
          echo "commit-date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
