name: Run ui tests
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
      
jobs:
  with-playwright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '9.0.x'

      - name: Remove local only content
        shell: pwsh
        working-directory: ./CourageScores/ClientApp
        run: ../../Scripts/Remove-LocalOnlyContent.ps1 -FilePath index.html

      - name: Copy sandbox launch configurations
        run: dotnet msbuild CourageScores.Sandbox/CourageScores.Sandbox.csproj -target:PreBuild
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_NOLOGO: true

      - name: Install playwright dependencies
        run: npm ci
        working-directory: ./CourageScores.BehaviouralTests/

      - name: Run prettier
        run: npx prettier --check -- .
        working-directory: ./CourageScores.BehaviouralTests/

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./CourageScores.BehaviouralTests/

      - name: Run Playwright tests
        run: npx playwright test --reporter=list
        working-directory: ./CourageScores.BehaviouralTests/

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./CourageScores.BehaviouralTests/playwright-report/
          retention-days: 1
