name: Upload

on:
  workflow_call:
    inputs:
      dotnet-root:
        required: true
        type: string

jobs:
  to-github:
    runs-on: windows-latest

    steps:
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ inputs.dotnet-root }}/myapp